### PR TITLE
Fixed Linux Compilation

### PR DESCRIPTION
**Pull request by WryOpussum**
I fixed linux compilation by renaming Goombone to goombone. And I also modified the readme on linux compilation to make EXTERNAL_DATA=1 -j

### CODE REVIEW

**Comment by WryOpussum** [comment]
HMm. Stopped compiling with n64 graphics. Let me see something. Might need to commit something.

**Comment by WryOpussum** [comment]
Ok fixed it. Ready to merge

**Comment by EmeraldLoc** [comment]
You modified WAY too many files, you removed a bunch of stuff, did you modify this repo, or create your own. actually modify THIS repo.

**Comment by EmeraldLoc** [comment]
If you fix it, then you can reopen the pr.

**Pull request closed without merging**
